{
  "swagger": "2.0",
  "info": {
    "version": "20.04",
    "title": "comdirect REST API",
    "description": "Please have a look at the interfaces of comdirect REST API below. Note: Currently it is not possible to request an access token via swagger UI tools because of comdirect's proprietary authorization flow. The shown error message is due to that circumstance."
  },
  "basePath": "/api",
  "host": "api.comdirect.de",
  "tags": [
    {
      "name": "Banking"
    },
    {
      "name": "Brokerage"
    },
    {
      "name": "Messages"
    },
    {
      "name": "Reports"
    },
    {
      "name": "Session"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/banking/clients/{user}/v2/accounts/balances": {
      "get": {
        "tags": [
          "Banking"
        ],
        "summary": "Request for account information, including cash balance and buying power, for all accounts",
        "description": "",
        "operationId": "bankingV2GetAccountBalances",
        "security": [
          {
            "CdSecondary": [
              "BANKING_RO"
            ]
          }
        ]
      }
    },
    "/banking/v1/accounts/{accountId}/transactions": {
      "get": {
        "tags": [
          "Banking"
        ],
        "summary": "Requests and returns a list of transactions for the given account",
        "description": "",
        "operationId": "bankingV1GetAccountTransactions",
        "security": [
          {
            "CdSecondary": [
              "BANKING_RO"
            ]
          }
        ]
      }
    },
    "/banking/v2/accounts/{accountId}/balances": {
      "get": {
        "tags": [
          "Banking"
        ],
        "summary": "Request for account information, including cash balance and buying power",
        "description": "",
        "operationId": "bankingV2GetAccountBalance",
        "security": [
          {
            "CdSecondary": [
              "BANKING_RO"
            ]
          }
        ]
      }
    },
    "/brokerage/clients/{userId}/v3/depots": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Request for a list of the master data for the securities accounts of the registered user",
        "description": "",
        "operationId": "brokerageV3GetDepots",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/depots/{depotId}/v3/orders": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Delivers a list of all orders for the given depotId.",
        "description": "",
        "operationId": "brokerageV3GetOrders",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v1/instruments/{instrumentId}": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Request for an instrument's information",
        "description": "",
        "operationId": "brokerageV1GetInstrument",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/depots/{depotId}/positions": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Request for securities positions, optionally including only the total balance with securities account information",
        "description": "",
        "operationId": "brokerageV3GetDepotPositions",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/depots/{depotId}/positions/{positionId}": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Request for retrieving a single position of specific depot.",
        "description": "",
        "operationId": "brokerageV3GetDepotPosition",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/depots/{depotId}/transactions": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Depot transactions.",
        "description": "",
        "operationId": "brokerageV3GetDepotTransactions",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Order entry.",
        "description": "",
        "operationId": "brokerageV3PostOrder",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/costindicationexante": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Generation of the ex-ante cost indication on the basis of the order data.",
        "description": "",
        "operationId": "brokerageV3GetOrdersCostIndicationExAnte",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/dimensions": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Request for the trading venue and order options for a particular instrument",
        "description": "",
        "operationId": "brokerageV3GetOrderDimensions",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/prevalidation": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Prevalidation of the order",
        "description": "",
        "operationId": "brokerageV3PostOrdersPrevalidation",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/validation": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Validation of an order entry and triggering of a TAN-Challenge in a non-usage case of a Session-TAN.",
        "description": "",
        "operationId": "brokerageV3PostOrdersValidation",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/{orderId}": {
      "get": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Delivers an order for the given orderId.",
        "description": "",
        "operationId": "brokerageV3GetOrder",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Order cancellation.",
        "description": "",
        "operationId": "brokerageV3DeleteOrder",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Order modification.",
        "description": "",
        "operationId": "brokerageV3PatchOrder",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/{orderId}/costindicationexante": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Generation of the ex-ante cost indication on the basis of the order data.",
        "description": "",
        "operationId": "brokerageV3GetOrderCostIndicationExAnte",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/{orderId}/prevalidation": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Prevalidation of an order modfication",
        "description": "",
        "operationId": "brokerageV3PostOrderPrevalidation",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/orders/{orderId}/validation": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Validation of an order modification or order cancellation and triggering of a TAN Challenge in a non-usage case of a Session-TAN.",
        "description": "",
        "operationId": "brokerageV3PostOrderValidation",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/quotes": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Sends a quote request to a venue",
        "description": "",
        "operationId": "brokerageV3PostQuoteRequest",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/quoteticket": {
      "post": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Initiates a TAN-Challenge",
        "description": "",
        "operationId": "brokerageV3PostQuoteTicket",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/brokerage/v3/quoteticket/{ticketId}": {
      "patch": {
        "tags": [
          "Brokerage"
        ],
        "summary": "Initiate a TAN-Challange",
        "description": "",
        "operationId": "brokerageV3PatchQuoteTicket",
        "security": [
          {
            "CdSecondary": [
              "BROKERAGE_RW"
            ]
          }
        ]
      }
    },
    "/messages/clients/{user}/v2/documents" : {
      "get" : {
        "tags" : [ "Messages" ],
        "summary" : "Delivers a list of documents for the customer.",
        "description" : "",
        "operationId" : "messagesV2GetDocuments",
        "security" : [
          {
            "CdSecondary" : [
              "MESSAGES_RO"
            ]
          }
        ]
      }
    },
    "/messages/v2/documents/{documentId}" : {
      "get" : {
        "tags" : [ "Messages" ],
        "summary" : "Delivers a document for the given UUID.",
        "description" : "",
        "operationId" : "messagesV2GetDocument",
        "security" : [
          {
            "CdSecondary" : [
              "MESSAGES_RO"
            ]
          }
        ]
      }
    },
    "/messages/v2/documents/{documentId}/predocument" : {
      "get" : {
        "tags" : [ "Messages" ],
        "summary" : "Delivers a predocument for the given UUID.",
        "description" : "",
        "operationId" : "messagesV2GetPredocument",
        "security" : [
          {
            "CdSecondary" : [
              "MESSAGES_RO"
            ]
          }
        ]
      }
    },
    "/reports/participants/{user}/v1/allbalances" : {
      "get" : {
        "tags" : [ "Reports" ],
        "summary" : "List of all balances for a client's own and connected products.",
        "description" : "",
        "operationId" : "reportsV1GetParticipantBalances",
        "security" : [
          {
            "CdSecondary": [
              "REPORTS_RO"
            ]
          }
        ]
      }
    },
    "/session/clients/{user}/v1/sessions": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "Returns the current Session-Objects for the specified client, can handle the literal \"user\" for the currently logged in client.",
        "description": "",
        "operationId": "sessionV1GetSession",
        "security": [
          {
            "ResourceOwnerPasswordCredentials": [
              "TWO_FACTOR"
            ]
          },
          {
            "CdSecondary": [
              "SESSION_RW"
            ]
          }
        ]
      }
    },
    "/session/clients/{user}/v1/sessions/{session}": {
      "patch": {
        "tags": [
          "Session"
        ],
        "summary": "Writes updates to a session",
        "description": "",
        "operationId": "sessionV1PatchSession",
        "security": [
          {
            "ResourceOwnerPasswordCredentials": [
              "TWO_FACTOR"
            ]
          },
          {
            "CdSecondary": [
              "SESSION_RW"
            ]
          }
        ]
      }
    },
    "/session/clients/{user}/v1/sessions/{session}/validate": {
      "post": {
        "tags": [
          "Session"
        ],
        "summary": "Validates the input and checks if the client is able to update the current session. An activated session TAN cannot be deactivated in the current session. It is necessary to provide a TAN when patching the activation of the session TAN.",
        "description": "",
        "operationId": "sessionV1PostSessionValidation",
        "security": [
          {
            "ResourceOwnerPasswordCredentials": [
              "TWO_FACTOR"
            ]
          },
          {
            "CdSecondary": [
              "SESSION_RW"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "ResourceOwnerPasswordCredentials": {
      "type": "oauth2",
      "flow": "password",
      "tokenUrl": "https://api.comdirect.de/oauth/token",
      "scopes": {
        "TWO_FACTOR": "Read and write permission for SESSION interfaces"
      }
    },
    "CdSecondary": {
      "type": "oauth2",
      "tokenUrl": "https://api.comdirect.de/oauth/token",
      "flow": "cd_secondary",
      "scopes": {
        "BANKING_RO": "Read permission for BANKING interfaces",
        "BROKERAGE_RW": "Read and write permission for BROKERAGE interfaces",
        "MESSAGES_RO": "Read permission for MESSAGES interfaces",
        "REPORTS_RO": "Read permission for REPORTS interfaces",
        "SESSION_RW": "Read and write permission for SESSION interfaces"
      }
    }
  }
}
